name: CI

on:
  push:
    branches:
      - main
      - changeset-release/**
      - release/**
  pull_request:
    branches:
      - "**"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  lint:
    uses: listee-dev/listee-ci/.github/workflows/lint.yml@main

  typecheck:
    uses: listee-dev/listee-ci/.github/workflows/typecheck.yml@main

  test:
    uses: listee-dev/listee-ci/.github/workflows/test.yml@main

  release:
    needs:
      - lint
      - typecheck
      - test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: listee-dev/listee-ci/.github/workflows/release.yml@main
    secrets: inherit
